// این آدرس را عمداً ثابت گذاشته‌ایم تا تنظیمات دستی نداشته باشی.
// هنگام ساخت سرویس Render، نام سرویس را دقیقاً "music-room-signaling" بگذار.
const SIGNALING_URL="wss://music-room-signaling.onrender.com";
const $=s=>document.querySelector(s);
const S={room:"",host:false,id:crypto.randomUUID(),ws:null,stream:null,peers:new Map()};
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>x.classList.remove("show"),2600)}
function show(x){document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));$("#"+x).classList.add("active")}
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function add(id,host){if(document.getElementById("m"+id))return;let d=document.createElement("div");d.id="m"+id;d.className="member";d.textContent=(host?"👑 ":"👤 ")+id.slice(0,8);$("#members").appendChild(d);$("#count").textContent=$("#members").children.length}
function rem(id){document.getElementById("m"+id)?.remove();$("#count").textContent=$("#members").children.length}
function send(x){S.ws?.send(JSON.stringify({...x,room:S.room,from:S.id}))}
function peer(id){if(S.peers.has(id))return S.peers.get(id);let p=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});if(S.stream)S.stream.getTracks().forEach(t=>p.addTrack(t,S.stream));p.onicecandidate=e=>e.candidate&&send({type:"ice",to:id,candidate:e.candidate});p.ontrack=e=>{let st=e.streams[0],v=$("#video"),a=$("#audio");v.srcObject=st;a.srcObject=st;v.classList.toggle("show",st.getVideoTracks().length>0);a.classList.toggle("show",st.getAudioTracks().length>0);$("#empty").style.display="none"};S.peers.set(id,p);return p}
async function offer(id){let p=peer(id),o=await p.createOffer();await p.setLocalDescription(o);send({type:"offer",to:id,offer:o})}
async function connect(){S.ws=new WebSocket(SIGNALING_URL);S.ws.onopen=()=>{send({type:"join",host:S.host});toast("به سرور وصل شد.")};S.ws.onmessage=async e=>{let m=JSON.parse(e.data);if(m.type==="members"){m.members.forEach(x=>add(x.id,x.host));if(S.host)for(let x of m.members)if(x.id!==S.id)await offer(x.id)}else if(m.type==="join"){add(m.id,m.host);if(S.host)await offer(m.id)}else if(m.type==="offer"){let p=peer(m.from);await p.setRemoteDescription(m.offer);let a=await p.createAnswer();await p.setLocalDescription(a);send({type:"answer",to:m.from,answer:a})}else if(m.type==="answer"){await S.peers.get(m.from)?.setRemoteDescription(m.answer)}else if(m.type==="ice"){try{await S.peers.get(m.from)?.addIceCandidate(m.candidate)}catch{}}else if(m.type==="leave"){rem(m.id);S.peers.get(m.id)?.close();S.peers.delete(m.id)}};S.ws.onerror=()=>toast("سرور هنوز آماده نیست یا نام سرویس درست نیست.");S.ws.onclose=()=>{}}
async function capture(mode){if(!S.host)return toast("فقط سرگروه می‌تواند اشتراک‌گذاری کند.");try{S.stream?.getTracks().forEach(t=>t.stop());let c=mode==="audio"?{video:false,audio:true}:mode==="screen"?{video:true,audio:false}:{video:true,audio:true};S.stream=await navigator.mediaDevices.getDisplayMedia(c);for(let [id,p] of S.peers){for(let s of p.getSenders())p.removeTrack(s);for(let t of S.stream.getTracks())p.addTrack(t,S.stream);await offer(id)}S.stream.getTracks().forEach(t=>t.onended=stop);toast("اشتراک‌گذاری فعال شد.")}catch{toast("اشتراک‌گذاری لغو شد.")}}
function stop(){S.stream?.getTracks().forEach(t=>t.stop());S.stream=null}
async function enter(r,h){S.room=r.toUpperCase();S.host=h;$("#roomCode").textContent=S.room;$("#title").textContent="اتاق "+S.room;$("#members").innerHTML="";add(S.id,h);history.replaceState({}, "", "#room="+S.room);show("room");await connect()}
$("#create").onclick=()=>enter(code(),true);$("#join").onclick=()=>{let c=$("#code").value.trim();c?enter(c,false):toast("کد اتاق را وارد کن.")};$("#audioBtn").onclick=()=>capture("audio");$("#screenBtn").onclick=()=>capture("screen");$("#bothBtn").onclick=()=>capture("both");$("#stop").onclick=()=>stop();$("#copy").onclick=async()=>{await navigator.clipboard.writeText(location.href.split("#")[0]+"#room="+S.room);toast("لینک کپی شد.")};$("#leave").onclick=()=>{S.ws?.close();stop();location.hash="";show("home")};let h=location.hash.match(/^#room=([A-Za-z0-9]+)$/);if(h)enter(h[1],false);
